package day42_Exceptions;

public class ThrowsKeyWord2 {
    public static void main(String[] args) throws InterruptedException{
        System.out.println("Test Started");
        System.out.println(8/0);
        System.out.println("Test Complete");
    }
}
